name: fractal_socket
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.4.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  frac:
    path: ../frac
  fractal:
    path: ../fractal
  signed_fractal:
    path: ../signed_fractal
  web_socket_channel: ^3.0.1

dev_dependencies:
  lints: ^4.0.0
